- id: doi:10.1016/j.envpol.2023.121419
  type: paper
  description: Reintroducing a keystone bioturbator can facilitate microbial bioremediation in urban polluted sediments
  date: 2023-5-1
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://www.sciencedirect.com/science/article/pii/S0269749123004219
    - type: website
      link: http://manubot.org/
  tags:
    - Bioturbators
    - collaboration

- id: 10.1016/j.envpol.2023.121419
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0269749123004219-ga1_lrg.jpg


