- id: doi:10.1016/j.envpol.2023.121419
  type: paper
  description: Reintroducing a keystone bioturbator can facilitate microbial bioremediation in urban polluted sediments
  date: 2023-5-1
  image: https://www.sciencedirect.com/science/article/pii/S0269749123004219?via%3Dihub
  buttons:
    - type: source
      text: Manuscript Source
      link: https://www.sciencedirect.com/science/article/pii/S0269749123004219
  tags:
    - Bioturbators
    - 16S Sequencing
    - DADA2

- id: https://doi.org/10.21203/rs.3.rs-3012963/v1
  type: paper
  description: Disentangling direct vs indirect effects of microbiome manipulations in a habitat-forming marine holobiont
  date: 2023-7-6
  image: https://www.sciencedirect.com/science/article/pii/S0269749123004219?via%3Dihub

  tags:
    - Experimental design
    - Causation
    - Host-microbe interactions
    - 16S Sequencing
    - DADA2


