- id: doi:10.1016/j.envpol.2023.121419
  type: paper
  description: Reintroducing a keystone bioturbator can facilitate microbial bioremediation in urban polluted sediments
  date: 2023-5-1
  image: https://www.sciencedirect.com/science/article/pii/S0269749123004219?via%3Dihub
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://www.sciencedirect.com/science/article/pii/S0269749123004219
    - type: website
      link: http://manubot.org/
  tags:
    - Bioturbators
    - 16S Sequencing
    - DADA2

- id: https://doi.org/10.1201/9781003288602
  


